name: masail_ka_hal
description: "Masail ka Hal - A Secure WebView Application"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.10.8 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  # ویب ویو کے لیے
  flutter_inappwebview: ^6.0.0 
  # جی پی ایس اور دیگر پرمیشنز کے لیے
  permission_handler: ^11.0.0 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  # ائیکون خود بخود سیٹ کرنے کے لیے
  flutter_launcher_icons: ^0.13.1 

# ائیکون کی سیٹنگ
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "icon.png" # یہ آپ کی اپلوڈ کردہ فائل استعمال کرے گا
  adaptive_icon_background: "#ffffff"

flutter:
  uses-material-design: true
